// Generated by scripts/gen_market_table.py --preset-ts. Do not edit by hand.
//
// A market is data, not code: the program is a schedule evaluator and
// never knows which market it is enforcing. Adding a market means adding
// a preset here, with no program upgrade and no new hook address.

/** Daylight-saving rule applied on top of the fixed offset. */
export const DstRule = { None: 0, US: 1, EU: 2 } as const;

export type Window = { daysMask: number; openMinute: number; closeMinute: number };
export type EarlyClose = { dayOffset: number; closeMinute: number };
/** Absolute-time override. Deny beats allow; both bounds are unix seconds. */
export type Event = { start: number; end: number; allow: boolean };
export type Market = {
  id: string;
  label: string;
  tzOffsetMinutes: number;
  dstRule: number;
  baseDay: number;
  windows: Window[];
  holidays: number[];
  earlyCloses: EarlyClose[];
  events: Event[];
};

/** Monday to Friday. Bit 0 is Sunday. */
const MON_TO_FRI = 0b0111110;

export const MARKETS: Record<string, Market> = {
  nyse: {
    id: "nyse",
    label: "NYSE — 09:30-16:00 ET, Mon-Fri",
    tzOffsetMinutes: -300,
    dstRule: DstRule.US,
    baseDay: 20454,
    windows: [{ daysMask: MON_TO_FRI, openMinute: 570, closeMinute: 960 }],
    holidays: [
      0, 18, 46, 92, 144, 169, 183, 249, 329, 358, 365, 382, 410, 449, 515, 533,
      550, 613, 693, 722, 746, 781, 834, 879, 900, 915, 977, 1057, 1089, 1096, 1110, 1145,
      1184, 1243, 1265, 1280, 1341, 1421, 1454, 1461, 1481, 1509, 1569, 1607, 1630, 1645, 1705, 1792,
      1819, 1826, 1845, 1873, 1926, 1971, 1995, 2010, 2069, 2156, 2184, 2191, 2209, 2237, 2276, 2342,
      2360, 2377, 2440, 2520, 2549, 2573, 2608, 2661, 2706, 2727, 2741, 2804, 2884, 2916, 2923, 2937,
      2972, 3018, 3070, 3091, 3106, 3168, 3248, 3280, 3287, 3301, 3336, 3368, 3434, 3456, 3471, 3532,
      3612, 3645, 3652, 3672, 3700, 3753, 3798, 3822, 3837, 3896, 3983, 4011, 4018, 4036, 4064, 4110,
      4162, 4187, 4201, 4267, 4347, 4376, 4383, 4400, 4428, 4495, 4533, 4551, 4568, 4631, 4711, 4740,
      4764, 4799, 4845, 4897, 4918, 4932, 4995, 5075, 5107, 5114, 5128, 5163, 5202, 5261, 5283, 5298,
      5359, 5439, 5472, 5479, 5499, 5527, 5587, 5625, 5648, 5663, 5723, 5810, 5837, 5844, 5863, 5891,
      5937, 5989, 6013, 6028, 6087, 6174, 6202, 6209, 6227, 6255, 6294, 6353, 6378, 6392, 6458, 6538,
      6567, 6574, 6591, 6619, 6679, 6724, 6745, 6759, 6822, 6902, 6934, 6941, 6955, 6990, 7036, 7088,
      7109, 7124, 7186, 7266, 7298, 7305, 7319, 7354, 7386, 7452, 7474, 7489, 7550, 7630, 7663,
    ],
    earlyCloses: [],
    events: [],
  },
  // SSE -- Shanghai Stock Exchange.
  //
  // Two sessions a day with a lunch break, and no daylight saving:
  // China has been a constant UTC+8 since 1991.
  //
  // Holidays are from exchange_calendars (XSHG), which ends 2026-12-31.
  // Chinese market holidays are announced annually by the State
  // Council and follow the lunar calendar, so unlike NYSE they cannot
  // be extrapolated. Past the last date above this schedule still
  // enforces weekends and both sessions, but stops blocking holidays.
  // A token copies its schedule at launch and cannot be updated, so
  // only launch on this while 2026-12-31 is comfortably ahead.
  sse: {
    id: "sse",
    label: "SSE \u2014 09:30-11:30, 13:00-15:00 CST, Mon-Fri",
    tzOffsetMinutes: 480,
    dstRule: DstRule.None,
    baseDay: 20454,
    windows: [
      { daysMask: MON_TO_FRI, openMinute: 570, closeMinute: 690 },  // 09:30-11:30
      { daysMask: MON_TO_FRI, openMinute: 780, closeMinute: 900 },  // 13:00-15:00
    ],
    holidays: [
      0, 1, 46, 47, 48, 49, 50, 53, 95, 120, 123, 124,
      169, 267, 273, 274, 277, 278, 279,
    ],
    earlyCloses: [],
    events: [],
  },
};

export function market(id: string): Market {
  const m = MARKETS[id];
  if (!m) throw new Error(`unknown market '${id}'. known: ${Object.keys(MARKETS).join(", ")}`);
  return m;
}
