use anchor_lang::prelude::*;
use anchor_spl::token_2022::spl_token_2022::{
    extension::{
        transfer_hook::TransferHookAccount, BaseStateWithExtensions, StateWithExtensions,
    },
    state::Account as Token2022Account,
};
use anchor_spl::token_interface;
use spl_tlv_account_resolution::{
    account::ExtraAccountMeta, seeds::Seed, state::ExtraAccountMetaList,
};
use spl_transfer_hook_interface::instruction::{ExecuteInstruction, TransferHookInstruction};

declare_id!("CUvtmRQZ6zikB7VijWzqS78orxrrkQhYkbhDL4PaPD6k");

#[cfg(test)]
mod market_tests;

/// Daylight-saving rule. Only the two that matter are implemented; everything
/// else is a fixed offset.
pub const DST_NONE: u8 = 0;
/// Second Sunday in March 02:00 local standard, to first Sunday in November
/// 02:00 local daylight. In force in the US since 2007.
pub const DST_US: u8 = 1;
/// Last Sunday in March 01:00 UTC to last Sunday in October 01:00 UTC.
pub const DST_EU: u8 = 2;

/// Schedules this program will accept, as sha256 of the Borsh-encoded
/// `ScheduleArgs`.
///
/// A market is data, but it is NOT free-form: `initialize` hashes the supplied
/// schedule and refuses anything not listed here. Nobody can launch a token on
/// this hook with hours of their own choosing, including us -- the list is
/// compiled in, so once the upgrade authority is burned it is fixed forever.
///
/// Adding a market therefore needs a new program with its own address. Tokens
/// already launched keep pointing at this one and are unaffected.
///
/// Generated by `npm run hash:markets`.
const ALLOWED_SCHEDULES: [[u8; 32]; 1] = [
    // NYSE, 09:30-16:00 ET Mon-Fri, US DST, holidays through 2046-12-25.
    [
        41, 177, 105, 54, 84, 251, 12, 232, 255, 202, 153, 77, 219, 30, 87, 182, 245, 187, 192,
        203, 107, 49, 40, 69, 235, 250, 219, 12, 142, 154, 237, 65,
    ],
];

const MAX_WINDOWS: usize = 14;
const MAX_HOLIDAYS: usize = 256;
const MAX_EARLY_CLOSES: usize = 64;
const MAX_EVENTS: usize = 64;

/// Bootstraps the market registry. Only this key can create the registry
/// account, after which the authority it names takes over and can be rotated.
///
/// This is the launch Ledger. Whoever holds it decides which markets may ever
/// be launched, and it is frozen once the upgrade authority is burned.
pub const REGISTRY_BOOTSTRAP: Pubkey = pubkey!("FTnprQrxXRGBAJRg8axCbocBNeSvQC3YoCFqEE8khJ3c");

#[program]
pub mod nyse_token_hook {
    use super::*;

    /// Write a mint's trading schedule and the hook's validation state.
    ///
    /// The schedule is written once and never mutated: there is no instruction
    /// to change it. A "market" is simply a preset the launcher supplies here,
    /// so new markets need no program upgrade, and changing a preset later
    /// cannot affect a token that has already launched.
    pub fn initialize(ctx: Context<Initialize>, args: ScheduleArgs) -> Result<()> {
        args.validate()?;
        // If a registry entry was supplied, it must be the PDA for this exact
        // schedule -- otherwise any registered market would approve any
        // schedule.
        if let Some(m) = ctx.accounts.market.as_ref() {
            let digest = anchor_lang::solana_program::hash::hash(&args.try_to_vec()?).to_bytes();
            let (expected, _) =
                Pubkey::find_program_address(&[b"market", digest.as_ref()], &crate::ID);
            require_keys_eq!(m.key(), expected, HookError::UnapprovedMarket);
        }
        args.assert_is_an_approved_market(ctx.accounts.market.as_deref())?;

        let s = &mut ctx.accounts.schedule;
        s.mint = ctx.accounts.mint.key();
        s.tz_offset_minutes = args.tz_offset_minutes;
        s.dst_rule = args.dst_rule;
        s.base_day = args.base_day;
        s.windows = args.windows;
        s.holidays = args.holidays;
        s.early_closes = args.early_closes;
        s.events = args.events;

        // Token-2022 must pass the schedule account on every transfer.
        let account_metas = vec![ExtraAccountMeta::new_with_seeds(
            &[
                Seed::Literal { bytes: b"schedule".to_vec() },
                Seed::AccountKey { index: 1 }, // the mint, in the Execute account list
            ],
            false,
            false,
        )?];

        let info = ctx.accounts.extra_account_meta_list.to_account_info();
        ExtraAccountMetaList::init::<ExecuteInstruction>(
            &mut info.try_borrow_mut_data()?,
            &account_metas,
        )?;

        msg!("schedule written for mint {}", s.mint);
        Ok(())
    }

    /// Create the market registry. Callable once, by REGISTRY_BOOTSTRAP.
    pub fn initialize_registry(ctx: Context<InitializeRegistry>, authority: Pubkey) -> Result<()> {
        ctx.accounts.registry.authority = authority;
        msg!("market registry authority: {}", authority);
        Ok(())
    }

    /// Hand the registry to a different key.
    pub fn set_registry_authority(
        ctx: Context<RegistryAdmin>,
        new_authority: Pubkey,
    ) -> Result<()> {
        ctx.accounts.registry.authority = new_authority;
        Ok(())
    }

    /// Approve a market so tokens may launch with it.
    ///
    /// This is the whole point of the registry: a new market is new DATA, so
    /// it needs no program upgrade and no new hook address. Approving or
    /// revoking one affects only FUTURE launches -- a token's schedule is
    /// copied into its own account at launch and nothing here can reach it.
    pub fn register_market(ctx: Context<RegisterMarket>, schedule_hash: [u8; 32]) -> Result<()> {
        ctx.accounts.market.schedule_hash = schedule_hash;
        msg!("market approved: {}", hex32(&schedule_hash));
        Ok(())
    }

    /// Stop new tokens launching with a market. Existing tokens are untouched.
    pub fn revoke_market(_ctx: Context<RevokeMarket>, _schedule_hash: [u8; 32]) -> Result<()> {
        Ok(())
    }

    /// Runs on every Token-2022 transfer of a mint configured with this hook.
    pub fn transfer_hook(ctx: Context<TransferHook>, _amount: u64) -> Result<()> {
        // Token-2022 sets this flag only for the duration of a real transfer
        // CPI, so it rejects a direct call to Execute.
        assert_is_transferring(&ctx.accounts.source_token.to_account_info())?;

        let now = Clock::get()?.unix_timestamp;
        match ctx.accounts.schedule.state_at(now) {
            MarketState::Open => Ok(()),
            MarketState::Holiday => {
                msg!("market closed: holiday");
                err!(HookError::MarketClosedHoliday)
            }
            MarketState::Closed => {
                msg!("market closed: outside trading hours");
                err!(HookError::MarketClosed)
            }
        }
    }

    /// Fallback dispatcher for the SPL transfer-hook interface, which uses its
    /// own instruction discriminators rather than Anchor's.
    pub fn fallback<'info>(
        program_id: &Pubkey,
        accounts: &'info [AccountInfo<'info>],
        data: &[u8],
    ) -> Result<()> {
        match TransferHookInstruction::unpack(data)? {
            TransferHookInstruction::Execute { amount } => {
                let amount_bytes = amount.to_le_bytes();
                __private::__global::transfer_hook(program_id, accounts, &amount_bytes)
            }
            _ => err!(HookError::UnsupportedInstruction),
        }
    }
}

fn assert_is_transferring(account_info: &AccountInfo) -> Result<()> {
    let data = account_info.try_borrow_data()?;
    let state = StateWithExtensions::<Token2022Account>::unpack(&data)
        .map_err(|_| error!(HookError::InvalidTokenAccount))?;
    let extension = state
        .get_extension::<TransferHookAccount>()
        .map_err(|_| error!(HookError::InvalidTokenAccount))?;

    if bool::from(extension.transferring) {
        Ok(())
    } else {
        err!(HookError::NotTransferring)
    }
}

// ---------------------------------------------------------------------------
// Accounts
// ---------------------------------------------------------------------------

#[account]
pub struct Registry {
    pub authority: Pubkey,
}

#[account]
pub struct Market {
    pub schedule_hash: [u8; 32],
}

#[derive(Accounts)]
pub struct InitializeRegistry<'info> {
    #[account(mut, address = REGISTRY_BOOTSTRAP @ HookError::NotRegistryAuthority)]
    pub payer: Signer<'info>,

    #[account(init, payer = payer, space = 8 + 32, seeds = [b"registry"], bump)]
    pub registry: Account<'info, Registry>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct RegistryAdmin<'info> {
    #[account(address = registry.authority @ HookError::NotRegistryAuthority)]
    pub authority: Signer<'info>,

    #[account(mut, seeds = [b"registry"], bump)]
    pub registry: Account<'info, Registry>,
}

#[derive(Accounts)]
#[instruction(schedule_hash: [u8; 32])]
pub struct RegisterMarket<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(address = registry.authority @ HookError::NotRegistryAuthority)]
    pub authority: Signer<'info>,

    #[account(seeds = [b"registry"], bump)]
    pub registry: Account<'info, Registry>,

    #[account(
        init,
        payer = payer,
        space = 8 + 32,
        seeds = [b"market", schedule_hash.as_ref()],
        bump
    )]
    pub market: Account<'info, Market>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(schedule_hash: [u8; 32])]
pub struct RevokeMarket<'info> {
    #[account(address = registry.authority @ HookError::NotRegistryAuthority)]
    pub authority: Signer<'info>,

    #[account(seeds = [b"registry"], bump)]
    pub registry: Account<'info, Registry>,

    /// CHECK: closed, rent returned to the authority.
    #[account(
        mut,
        close = authority,
        seeds = [b"market", schedule_hash.as_ref()],
        bump
    )]
    pub market: Account<'info, Market>,
}

/// Lowercase hex, for log messages.
fn hex32(bytes: &[u8; 32]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(64);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

#[derive(Accounts)]
#[instruction(args: ScheduleArgs)]
pub struct Initialize<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        init,
        payer = payer,
        space = Schedule::space(
            args.windows.len(),
            args.holidays.len(),
            args.early_closes.len(),
            args.events.len(),
        ),
        seeds = [b"schedule", mint.key().as_ref()],
        bump
    )]
    pub schedule: Account<'info, Schedule>,

    /// CHECK: initialized here as a TLV ExtraAccountMetaList; seeds are checked.
    #[account(
        init,
        payer = payer,
        space = ExtraAccountMetaList::size_of(1)?,
        seeds = [b"extra-account-metas", mint.key().as_ref()],
        bump
    )]
    pub extra_account_meta_list: AccountInfo<'info>,

    /// CHECK: only used for PDA derivation and recorded on the schedule.
    pub mint: AccountInfo<'info>,

    /// Needed only for a market that is registered rather than compiled in.
    /// Its address is checked against the schedule hash in the handler, since
    /// a seeds constraint cannot run the fallible encoding.
    pub market: Option<Account<'info, Market>>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct TransferHook<'info> {
    #[account(token::mint = mint)]
    pub source_token: InterfaceAccount<'info, token_interface::TokenAccount>,

    pub mint: InterfaceAccount<'info, token_interface::Mint>,

    #[account(token::mint = mint)]
    pub destination_token: InterfaceAccount<'info, token_interface::TokenAccount>,

    /// The transfer authority. NOT necessarily the source account's owner: for
    /// delegated transfers Token-2022 passes the delegate here.
    /// CHECK: not authorizing anything on it.
    pub authority: UncheckedAccount<'info>,

    /// CHECK: unused; present only to match the transfer-hook account layout.
    pub extra_account_meta_list: UncheckedAccount<'info>,

    /// The mint's immutable trading schedule.
    #[account(seeds = [b"schedule", mint.key().as_ref()], bump)]
    pub schedule: Account<'info, Schedule>,
}

// ---------------------------------------------------------------------------
// Schedule
// ---------------------------------------------------------------------------

/// One recurring weekly opening, in the market's local time.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct Window {
    /// Bit 0 = Sunday ... bit 6 = Saturday.
    pub days_mask: u8,
    /// Minutes from local midnight, inclusive.
    pub open_minute: u16,
    /// Minutes from local midnight, exclusive.
    pub close_minute: u16,
}

/// An absolute-time override, evaluated before the weekly windows.
///
/// Both bounds are unix seconds. A `deny` event closes the market for that
/// span whatever the windows say; an `allow` event opens it. Deny wins if two
/// overlap. Because a schedule is immutable, events must be known at launch:
/// they cannot be used to react to an unscheduled closure later.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct Event {
    pub start: i64,
    /// Exclusive.
    pub end: i64,
    /// true opens the market for the span, false closes it.
    pub allow: bool,
}

/// A day that closes earlier than its window would allow.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct EarlyClose {
    /// Days after `base_day`.
    pub day_offset: u16,
    /// Minutes from local midnight, exclusive.
    pub close_minute: u16,
}

/// Instruction payload. Mirrors `Schedule` minus the mint.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug)]
pub struct ScheduleArgs {
    pub tz_offset_minutes: i16,
    pub dst_rule: u8,
    pub base_day: i32,
    pub windows: Vec<Window>,
    /// Full closures, as days after `base_day`, sorted ascending.
    pub holidays: Vec<u16>,
    pub early_closes: Vec<EarlyClose>,
    pub events: Vec<Event>,
}

impl ScheduleArgs {
    /// Reject any schedule that is neither compiled in nor registered.
    ///
    /// Two sources of truth, deliberately. The compiled list means the
    /// launch market keeps working even if the registry key is lost; the
    /// registry means later markets need no new program.
    fn assert_is_an_approved_market(&self, market: Option<&Market>) -> Result<()> {
        let digest = anchor_lang::solana_program::hash::hash(&self.try_to_vec()?).to_bytes();

        if ALLOWED_SCHEDULES.iter().any(|h| *h == digest) {
            return Ok(());
        }
        if let Some(m) = market {
            if m.schedule_hash == digest {
                return Ok(());
            }
        }
        err!(HookError::UnapprovedMarket)
    }

    fn validate(&self) -> Result<()> {
        require!(!self.windows.is_empty(), HookError::NoWindows);
        require!(self.windows.len() <= MAX_WINDOWS, HookError::TooManyWindows);
        require!(self.holidays.len() <= MAX_HOLIDAYS, HookError::TooManyHolidays);
        require!(
            self.early_closes.len() <= MAX_EARLY_CLOSES,
            HookError::TooManyEarlyCloses
        );
        require!(self.events.len() <= MAX_EVENTS, HookError::TooManyEvents);
        for e in &self.events {
            require!(e.start < e.end, HookError::InvalidEvent);
        }
        require!(self.dst_rule <= DST_EU, HookError::InvalidDstRule);
        require!(
            self.tz_offset_minutes >= -720 && self.tz_offset_minutes <= 840,
            HookError::InvalidTimezoneOffset
        );
        for w in &self.windows {
            require!(w.days_mask != 0, HookError::InvalidWindow);
            require!(w.open_minute < w.close_minute, HookError::InvalidWindow);
            require!(w.close_minute <= 1440, HookError::InvalidWindow);
        }
        // Binary search over holidays requires sorted input.
        require!(
            self.holidays.windows(2).all(|p| p[0] < p[1]),
            HookError::HolidaysNotSorted
        );
        Ok(())
    }
}

#[account]
pub struct Schedule {
    pub mint: Pubkey,
    pub tz_offset_minutes: i16,
    pub dst_rule: u8,
    pub base_day: i32,
    pub windows: Vec<Window>,
    pub holidays: Vec<u16>,
    pub early_closes: Vec<EarlyClose>,
    pub events: Vec<Event>,
}

impl Schedule {
    pub fn space(
        windows: usize,
        holidays: usize,
        early_closes: usize,
        events: usize,
    ) -> usize {
        8  // discriminator
        + 32 // mint
        + 2  // tz_offset_minutes
        + 1  // dst_rule
        + 4  // base_day
        + 4 + windows * 5
        + 4 + holidays * 2
        + 4 + early_closes * 4
        + 4 + events * 17
    }

    /// Market state at a UTC timestamp.
    pub fn state_at(&self, utc_ts: i64) -> MarketState {
        // Absolute-time overrides come first. A deny beats an allow.
        let mut allowed_by_event = false;
        for e in self.events.iter() {
            if utc_ts >= e.start && utc_ts < e.end {
                if !e.allow {
                    return MarketState::Closed;
                }
                allowed_by_event = true;
            }
        }
        if allowed_by_event {
            return MarketState::Open;
        }

        let offset_minutes = self.tz_offset_minutes as i64 + if self.is_dst(utc_ts) { 60 } else { 0 };
        let local = utc_ts + offset_minutes * 60;

        let day = local.div_euclid(86_400);
        let minute_of_day = (local.rem_euclid(86_400) / 60) as u16;
        let weekday = weekday_from_days(day);

        // Holidays and early closes are stored as offsets from base_day.
        let offset = day - self.base_day as i64;
        let day_offset: Option<u16> = if (0..=u16::MAX as i64).contains(&offset) {
            Some(offset as u16)
        } else {
            None
        };

        if let Some(d) = day_offset {
            if self.holidays.binary_search(&d).is_ok() {
                return MarketState::Holiday;
            }
        }

        let mut close = None;
        for w in self.windows.iter() {
            if w.days_mask & (1 << weekday) == 0 {
                continue;
            }
            if minute_of_day >= w.open_minute && minute_of_day < w.close_minute {
                close = Some(w.close_minute);
                break;
            }
        }
        let Some(mut close_minute) = close else {
            return MarketState::Closed;
        };

        if let Some(d) = day_offset {
            if let Some(ec) = self.early_closes.iter().find(|e| e.day_offset == d) {
                close_minute = close_minute.min(ec.close_minute);
            }
        }

        if minute_of_day < close_minute {
            MarketState::Open
        } else {
            MarketState::Closed
        }
    }

    fn is_dst(&self, utc_ts: i64) -> bool {
        match self.dst_rule {
            DST_US => {
                // Both boundaries are defined in LOCAL time, so convert each to
                // UTC and compare there. The start is 02:00 local *standard*
                // time; the end is 02:00 local *daylight* time, which is one
                // hour earlier in UTC terms.
                let off = self.tz_offset_minutes as i64 * 60;
                // Transitions sit far from 1 January, so the UTC year is safe.
                let (year, _, _) = civil_from_days(utc_ts.div_euclid(86_400));
                let start = days_from_civil(year, 3, nth_weekday(year, 3, 0, 2)) * 86_400
                    + 2 * 3_600
                    - off;
                let end = days_from_civil(year, 11, nth_weekday(year, 11, 0, 1)) * 86_400
                    + 2 * 3_600
                    - off
                    - 3_600;
                utc_ts >= start && utc_ts < end
            }
            DST_EU => {
                // Both EU transitions are defined in UTC, which makes this exact.
                let (year, _, _) = civil_from_days(utc_ts.div_euclid(86_400));
                let start = days_from_civil(year, 3, last_weekday(year, 3, 0)) * 86_400 + 3_600;
                let end = days_from_civil(year, 10, last_weekday(year, 10, 0)) * 86_400 + 3_600;
                utc_ts >= start && utc_ts < end
            }
            _ => false,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MarketState {
    Open,
    Holiday,
    Closed,
}

#[error_code]
pub enum HookError {
    #[msg("market closed: outside trading hours")]
    MarketClosed,
    #[msg("market closed: holiday")]
    MarketClosedHoliday,
    #[msg("hook invoked outside of a transfer")]
    NotTransferring,
    #[msg("could not parse Token-2022 account state")]
    InvalidTokenAccount,
    #[msg("unsupported transfer hook instruction")]
    UnsupportedInstruction,
    #[msg("schedule must define at least one window")]
    NoWindows,
    #[msg("too many windows")]
    TooManyWindows,
    #[msg("too many holidays")]
    TooManyHolidays,
    #[msg("too many early closes")]
    TooManyEarlyCloses,
    #[msg("unknown daylight-saving rule")]
    InvalidDstRule,
    #[msg("timezone offset out of range")]
    InvalidTimezoneOffset,
    #[msg("window is malformed")]
    InvalidWindow,
    #[msg("holidays must be sorted ascending with no duplicates")]
    HolidaysNotSorted,
    #[msg("schedule is not an approved market")]
    UnapprovedMarket,
    #[msg("too many events")]
    TooManyEvents,
    #[msg("event is malformed")]
    InvalidEvent,
    #[msg("only the registry authority may do this")]
    NotRegistryAuthority,
}

// ---------------------------------------------------------------------------
// Civil calendar: Howard Hinnant's algorithms, leap-year exact.
// http://howardhinnant.github.io/date_algorithms.html
// ---------------------------------------------------------------------------

pub fn days_from_civil(y: i32, m: u32, d: u32) -> i64 {
    let y = y - if m <= 2 { 1 } else { 0 };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = (y - era * 400) as i64;
    let mp = ((m + 9) % 12) as i64;
    let doy = (153 * mp + 2) / 5 + d as i64 - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era as i64 * 146_097 + doe - 719_468
}

pub fn civil_from_days(z: i64) -> (i32, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    ((y + if m <= 2 { 1 } else { 0 }) as i32, m, d)
}

/// 0 = Sunday .. 6 = Saturday. 1970-01-01 was a Thursday.
pub fn weekday_from_days(days: i64) -> u32 {
    (days + 4).rem_euclid(7) as u32
}

/// Day-of-month of the `n`-th `weekday` (0 = Sunday) in the given month.
pub fn nth_weekday(year: i32, month: u32, weekday: u32, n: u32) -> u32 {
    let first = days_from_civil(year, month, 1);
    let offset = (weekday + 7 - weekday_from_days(first)) % 7;
    1 + offset + (n - 1) * 7
}

/// Day-of-month of the last `weekday` (0 = Sunday) in the given month.
pub fn last_weekday(year: i32, month: u32, weekday: u32) -> u32 {
    let (ny, nm) = if month == 12 { (year + 1, 1) } else { (year, month + 1) };
    let last = days_from_civil(ny, nm, 1) - 1;
    let back = (weekday_from_days(last) + 7 - weekday) % 7;
    let (_, _, dom) = civil_from_days(last - back as i64);
    dom
}
