//! Unit tests for the schedule evaluator.
//!
//! The NYSE preset and the session table are both generated from the IANA tz
//! database by `scripts/gen_market_table.py`, so neither is written by hand and
//! neither depends on the code under test.

use super::*;

// Generated by scripts/gen_market_table.py -- do not edit by hand.
//
// NYSE, 2026-2046. Holidays are stored as day offsets from
// base_day, so the program needs no calendar logic and new markets need no
// program upgrade. Last holiday covered: 2046-12-25.
#[cfg(test)]
pub fn nyse_schedule() -> Schedule {
    Schedule {
        mint: Pubkey::default(),
        tz_offset_minutes: -300, // EST; DST_US adds the hour
        dst_rule: DST_US,
        base_day: 20454, // 2026-01-01
        // Monday to Friday, 09:30-16:00 local.
        windows: vec![Window { days_mask: 0b0111110, open_minute: 570, close_minute: 960 }],
        holidays: vec![
            0, 18, 46, 92, 144, 169, 183, 249, 329, 358, 365, 382,
            410, 449, 515, 533, 550, 613, 693, 722, 746, 781, 834, 879,
            900, 915, 977, 1057, 1089, 1096, 1110, 1145, 1184, 1243, 1265, 1280,
            1341, 1421, 1454, 1461, 1481, 1509, 1569, 1607, 1630, 1645, 1705, 1792,
            1819, 1826, 1845, 1873, 1926, 1971, 1995, 2010, 2069, 2156, 2184, 2191,
            2209, 2237, 2276, 2342, 2360, 2377, 2440, 2520, 2549, 2573, 2608, 2661,
            2706, 2727, 2741, 2804, 2884, 2916, 2923, 2937, 2972, 3018, 3070, 3091,
            3106, 3168, 3248, 3280, 3287, 3301, 3336, 3368, 3434, 3456, 3471, 3532,
            3612, 3645, 3652, 3672, 3700, 3753, 3798, 3822, 3837, 3896, 3983, 4011,
            4018, 4036, 4064, 4110, 4162, 4187, 4201, 4267, 4347, 4376, 4383, 4400,
            4428, 4495, 4533, 4551, 4568, 4631, 4711, 4740, 4764, 4799, 4845, 4897,
            4918, 4932, 4995, 5075, 5107, 5114, 5128, 5163, 5202, 5261, 5283, 5298,
            5359, 5439, 5472, 5479, 5499, 5527, 5587, 5625, 5648, 5663, 5723, 5810,
            5837, 5844, 5863, 5891, 5937, 5989, 6013, 6028, 6087, 6174, 6202, 6209,
            6227, 6255, 6294, 6353, 6378, 6392, 6458, 6538, 6567, 6574, 6591, 6619,
            6679, 6724, 6745, 6759, 6822, 6902, 6934, 6941, 6955, 6990, 7036, 7088,
            7109, 7124, 7186, 7266, 7298, 7305, 7319, 7354, 7386, 7452, 7474, 7489,
            7550, 7630, 7663,
        ],
        // NYSE half-days are deliberately not enforced.
        early_closes: vec![],
        events: vec![],
    }
}

#[test]
fn civil_roundtrip_covers_leap_years() {
    let start = days_from_civil(2024, 1, 1);
    let end = days_from_civil(2048, 1, 1);
    for z in start..end {
        let (y, m, d) = civil_from_days(z);
        assert_eq!(days_from_civil(y, m, d), z, "roundtrip failed at {y}-{m:02}-{d:02}");
    }
}

#[test]
fn known_civil_dates() {
    assert_eq!(days_from_civil(1970, 1, 1), 0);
    assert_eq!(civil_from_days(0), (1970, 1, 1));
    assert_eq!(civil_from_days(days_from_civil(2028, 2, 29)), (2028, 2, 29));
    assert_eq!(days_from_civil(2028, 3, 1) - days_from_civil(2028, 2, 28), 2);
    // 2100 is not a leap year.
    assert_eq!(days_from_civil(2100, 3, 1) - days_from_civil(2100, 2, 28), 1);
}

#[test]
fn weekdays_and_nth_weekday() {
    assert_eq!(weekday_from_days(0), 4); // 1970-01-01 was a Thursday
    assert_eq!(weekday_from_days(days_from_civil(2026, 9, 28)), 1); // Monday
    assert_eq!(nth_weekday(2026, 1, 1, 3), 19); // third Monday of Jan 2026
    assert_eq!(nth_weekday(2026, 11, 4, 4), 26); // fourth Thursday of Nov 2026
    assert_eq!(last_weekday(2026, 5, 1), 25); // last Monday of May 2026
    assert_eq!(last_weekday(2026, 3, 0), 29); // last Sunday of March 2026
}

#[test]
fn us_dst_transitions_are_exact() {
    let s = nyse_schedule();
    // (dst start, dst end) in UTC, verified against tzdata.
    for (year, start, end) in [
        (2026, 1_772_953_200i64, 1_793_512_800i64),
        (2027, 1_805_007_600, 1_825_567_200),
        (2028, 1_836_457_200, 1_857_016_800),
    ] {
        assert!(!s.is_dst(start - 1), "{year}: DST began early");
        assert!(s.is_dst(start), "{year}: DST did not begin on time");
        assert!(s.is_dst(end - 1), "{year}: DST ended early");
        assert!(!s.is_dst(end), "{year}: DST did not end on time");
    }
}

#[test]
fn eu_dst_transitions_are_exact() {
    let s = Schedule {
        mint: Pubkey::default(),
        tz_offset_minutes: 0,
        dst_rule: DST_EU,
        base_day: 0,
        windows: vec![Window { days_mask: 0b0111110, open_minute: 480, close_minute: 990 }],
        holidays: vec![],
        early_closes: vec![],
        events: vec![],
    };
    // Last Sunday in March / October at 01:00 UTC.
    for (year, m_start, d_start, m_end, d_end) in
        [(2026u32 as i32, 3u32, 29u32, 10u32, 25u32), (2027, 3, 28, 10, 31)]
    {
        let start = days_from_civil(year, m_start, d_start) * 86_400 + 3_600;
        let end = days_from_civil(year, m_end, d_end) * 86_400 + 3_600;
        assert!(!s.is_dst(start - 1), "{year}: EU DST began early");
        assert!(s.is_dst(start), "{year}: EU DST did not begin");
        assert!(s.is_dst(end - 1), "{year}: EU DST ended early");
        assert!(!s.is_dst(end), "{year}: EU DST did not end");
    }
}

#[test]
fn a_market_with_no_dst_never_shifts() {
    let tokyo = Schedule {
        mint: Pubkey::default(),
        tz_offset_minutes: 9 * 60,
        dst_rule: DST_NONE,
        base_day: 0,
        windows: vec![Window { days_mask: 0b0111110, open_minute: 540, close_minute: 900 }],
        holidays: vec![],
        early_closes: vec![],
        events: vec![],
    };
    for ts in [1_772_953_200i64, 1_793_512_800, 1_805_007_600] {
        assert!(!tokyo.is_dst(ts));
    }
}

#[test]
fn schedule_args_are_validated() {
    let ok = ScheduleArgs {
        tz_offset_minutes: -300,
        dst_rule: DST_US,
        base_day: 20454,
        windows: vec![Window { days_mask: 0b0111110, open_minute: 570, close_minute: 960 }],
        holidays: vec![1, 2, 3],
        early_closes: vec![],
        events: vec![],
    };
    assert!(ok.validate().is_ok());

    let no_windows = ScheduleArgs { windows: vec![], ..ok.clone() };
    assert!(no_windows.validate().is_err(), "a schedule with no windows must be rejected");

    let unsorted = ScheduleArgs { holidays: vec![5, 3, 9], ..ok.clone() };
    assert!(unsorted.validate().is_err(), "unsorted holidays break the binary search");

    let dup = ScheduleArgs { holidays: vec![3, 3], ..ok.clone() };
    assert!(dup.validate().is_err());

    let backwards = ScheduleArgs {
        windows: vec![Window { days_mask: 0b0111110, open_minute: 960, close_minute: 570 }],
        ..ok.clone()
    };
    assert!(backwards.validate().is_err());

    let bad_dst = ScheduleArgs { dst_rule: 9, ..ok.clone() };
    assert!(bad_dst.validate().is_err());

    let bad_tz = ScheduleArgs { tz_offset_minutes: 2000, ..ok };
    assert!(bad_tz.validate().is_err());
}

#[test]
fn nyse_session_table() {
    let s = nyse_schedule();
    const SESSIONS: &[(i64, MarketState)] = &[
        // Every NYSE full closure 2026-2028, checked at 11:00 ET
        (1767283200, MarketState::Holiday),               // 2026-01-01 Thu 11:00 ET NewYears
        (1768838400, MarketState::Holiday),               // 2026-01-19 Mon 11:00 ET MLK
        (1771257600, MarketState::Holiday),               // 2026-02-16 Mon 11:00 ET Presidents
        (1775228400, MarketState::Holiday),               // 2026-04-03 Fri 11:00 ET GoodFriday
        (1779721200, MarketState::Holiday),               // 2026-05-25 Mon 11:00 ET Memorial
        (1781881200, MarketState::Holiday),               // 2026-06-19 Fri 11:00 ET Juneteenth
        (1783090800, MarketState::Holiday),               // 2026-07-03 Fri 11:00 ET Independence
        (1788793200, MarketState::Holiday),               // 2026-09-07 Mon 11:00 ET Labor
        (1795708800, MarketState::Holiday),               // 2026-11-26 Thu 11:00 ET Thanksgiving
        (1798214400, MarketState::Holiday),               // 2026-12-25 Fri 11:00 ET Christmas
        (1798819200, MarketState::Holiday),               // 2027-01-01 Fri 11:00 ET NewYears
        (1800288000, MarketState::Holiday),               // 2027-01-18 Mon 11:00 ET MLK
        (1802707200, MarketState::Holiday),               // 2027-02-15 Mon 11:00 ET Presidents
        (1806073200, MarketState::Holiday),               // 2027-03-26 Fri 11:00 ET GoodFriday
        (1811775600, MarketState::Holiday),               // 2027-05-31 Mon 11:00 ET Memorial
        (1813330800, MarketState::Holiday),               // 2027-06-18 Fri 11:00 ET Juneteenth
        (1814799600, MarketState::Holiday),               // 2027-07-05 Mon 11:00 ET Independence
        (1820242800, MarketState::Holiday),               // 2027-09-06 Mon 11:00 ET Labor
        (1827158400, MarketState::Holiday),               // 2027-11-25 Thu 11:00 ET Thanksgiving
        (1829664000, MarketState::Holiday),               // 2027-12-24 Fri 11:00 ET Christmas
        (1831737600, MarketState::Holiday),               // 2028-01-17 Mon 11:00 ET MLK
        (1834761600, MarketState::Holiday),               // 2028-02-21 Mon 11:00 ET Presidents
        (1839337200, MarketState::Holiday),               // 2028-04-14 Fri 11:00 ET GoodFriday
        (1843225200, MarketState::Holiday),               // 2028-05-29 Mon 11:00 ET Memorial
        (1845039600, MarketState::Holiday),               // 2028-06-19 Mon 11:00 ET Juneteenth
        (1846335600, MarketState::Holiday),               // 2028-07-04 Tue 11:00 ET Independence
        (1851692400, MarketState::Holiday),               // 2028-09-04 Mon 11:00 ET Labor
        (1858608000, MarketState::Holiday),               // 2028-11-23 Thu 11:00 ET Thanksgiving
        (1861372800, MarketState::Holiday),               // 2028-12-25 Mon 11:00 ET Christmas

        // NYSE half-days (13:00 ET close). We deliberately do NOT enforce these:
        // the session stays 09:30-16:00, so 15:00 ET is still Open.
        (1795802340, MarketState::Open),                  // 2026-11-27 Fri 12:59 ET DayAfterThanksgiving
        (1795802400, MarketState::Open),                  // 2026-11-27 Fri 13:00 ET DayAfterThanksgiving
        (1795809600, MarketState::Open),                  // 2026-11-27 Fri 15:00 ET DayAfterThanksgiving
        (1798135140, MarketState::Open),                  // 2026-12-24 Thu 12:59 ET ChristmasEve
        (1798135200, MarketState::Open),                  // 2026-12-24 Thu 13:00 ET ChristmasEve
        (1798142400, MarketState::Open),                  // 2026-12-24 Thu 15:00 ET ChristmasEve
        (1827251940, MarketState::Open),                  // 2027-11-26 Fri 12:59 ET DayAfterThanksgiving
        (1827252000, MarketState::Open),                  // 2027-11-26 Fri 13:00 ET DayAfterThanksgiving
        (1827259200, MarketState::Open),                  // 2027-11-26 Fri 15:00 ET DayAfterThanksgiving
        (1846256340, MarketState::Open),                  // 2028-07-03 Mon 12:59 ET July3
        (1846256400, MarketState::Open),                  // 2028-07-03 Mon 13:00 ET July3
        (1846263600, MarketState::Open),                  // 2028-07-03 Mon 15:00 ET July3
        (1858701540, MarketState::Open),                  // 2028-11-24 Fri 12:59 ET DayAfterThanksgiving
        (1858701600, MarketState::Open),                  // 2028-11-24 Fri 13:00 ET DayAfterThanksgiving
        (1858708800, MarketState::Open),                  // 2028-11-24 Fri 15:00 ET DayAfterThanksgiving

        // Regular session edges on an ordinary Monday
        (1790602140, MarketState::Closed),             // 2026-09-28 Mon 09:29 ET 
        (1790602200, MarketState::Open),                  // 2026-09-28 Mon 09:30 ET 
        (1790602260, MarketState::Open),                  // 2026-09-28 Mon 09:31 ET 
        (1790625540, MarketState::Open),                  // 2026-09-28 Mon 15:59 ET 
        (1790625600, MarketState::Closed),            // 2026-09-28 Mon 16:00 ET 
        (1790625660, MarketState::Closed),            // 2026-09-28 Mon 16:01 ET 
        (1790568000, MarketState::Closed),             // 2026-09-28 Mon 00:00 ET 
        (1790654340, MarketState::Closed),            // 2026-09-28 Mon 23:59 ET 

        // Weekend
        (1790434800, MarketState::Closed),               // 2026-09-26 Sat 11:00 ET 
        (1790521200, MarketState::Closed),               // 2026-09-27 Sun 11:00 ET 

        // Across both DST transitions: 09:30 and 15:59 ET must stay in session
        (1772807400, MarketState::Open),                  // 2026-03-06 Fri 09:30 ET 
        (1772830740, MarketState::Open),                  // 2026-03-06 Fri 15:59 ET 
        (1773063000, MarketState::Open),                  // 2026-03-09 Mon 09:30 ET 
        (1773086340, MarketState::Open),                  // 2026-03-09 Mon 15:59 ET 
        (1793367000, MarketState::Open),                  // 2026-10-30 Fri 09:30 ET 
        (1793390340, MarketState::Open),                  // 2026-10-30 Fri 15:59 ET 
        (1793629800, MarketState::Open),                  // 2026-11-02 Mon 09:30 ET 
        (1793653140, MarketState::Open),                  // 2026-11-02 Mon 15:59 ET 
        (1804861800, MarketState::Open),                  // 2027-03-12 Fri 09:30 ET 
        (1804885140, MarketState::Open),                  // 2027-03-12 Fri 15:59 ET 
        (1805117400, MarketState::Open),                  // 2027-03-15 Mon 09:30 ET 
        (1805140740, MarketState::Open),                  // 2027-03-15 Mon 15:59 ET 
        (1825421400, MarketState::Open),                  // 2027-11-05 Fri 09:30 ET 
        (1825444740, MarketState::Open),                  // 2027-11-05 Fri 15:59 ET 
        (1825684200, MarketState::Open),                  // 2027-11-08 Mon 09:30 ET 
        (1825707540, MarketState::Open),                  // 2027-11-08 Mon 15:59 ET 

        // Regression: dates the old 365-day-year math got wrong
        (1797004800, MarketState::Open),                  // 2026-12-11 Fri 11:00 ET old code falsely blocked as Christmas
        (1797000300, MarketState::Open),                  // 2026-12-11 Fri 09:45 ET old code falsely blocked as Christmas
        (1797609600, MarketState::Open),                  // 2026-12-18 Fri 11:00 ET old code falsely blocked as New Years
        (1797605100, MarketState::Open),                  // 2026-12-18 Fri 09:45 ET old code falsely blocked as New Years
        (1792508400, MarketState::Open),                  // 2026-10-20 Tue 11:00 ET old code had DST wrong -> window shifted
        (1792503900, MarketState::Open),                  // 2026-10-20 Tue 09:45 ET old code had DST wrong -> window shifted
        (1793372400, MarketState::Open),                  // 2026-10-30 Fri 11:00 ET old code had DST wrong -> window shifted
        (1793367900, MarketState::Open),                  // 2026-10-30 Fri 09:45 ET old code had DST wrong -> window shifted

    ];

    for &(ts, want) in SESSIONS {
        let got = s.state_at(ts);
        assert_eq!(got, want, "ts {ts}: expected {want:?}, got {got:?}");
    }
}

#[test]
fn session_is_a_uniform_window_on_every_trading_day() {
    let s = nyse_schedule();
    let start = days_from_civil(2026, 1, 1);
    let end = days_from_civil(2031, 1, 1);
    for z in start..end {
        let wd = weekday_from_days(z);
        let offset = (z - s.base_day as i64) as u16;
        if wd == 0 || wd == 6 || s.holidays.binary_search(&offset).is_ok() {
            continue;
        }
        let dst = s.is_dst(z * 86_400 + 12 * 3_600);
        let base = z * 86_400 + (if dst { 4 } else { 5 }) * 3_600;
        let at = |min: i64| base + min * 60;
        let (y, m, d) = civil_from_days(z);
        assert_eq!(s.state_at(at(9 * 60 + 29)), MarketState::Closed, "{y}-{m:02}-{d:02} 09:29");
        assert_eq!(s.state_at(at(9 * 60 + 30)), MarketState::Open, "{y}-{m:02}-{d:02} 09:30");
        assert_eq!(s.state_at(at(15 * 60 + 59)), MarketState::Open, "{y}-{m:02}-{d:02} 15:59");
        assert_eq!(s.state_at(at(16 * 60)), MarketState::Closed, "{y}-{m:02}-{d:02} 16:00");
    }
}

#[test]
fn early_close_shortens_the_day() {
    let mut s = nyse_schedule();
    // 2026-11-27, the Friday after Thanksgiving.
    let day = days_from_civil(2026, 11, 27);
    let offset = (day - s.base_day as i64) as u16;
    s.early_closes = vec![EarlyClose { day_offset: offset, close_minute: 780 }]; // 13:00
    let base = day * 86_400 + 5 * 3_600; // EST in November
    assert_eq!(s.state_at(base + (12 * 60 + 59) * 60), MarketState::Open);
    assert_eq!(s.state_at(base + 13 * 3_600), MarketState::Closed);
}

#[test]
fn holidays_outside_the_horizon_do_not_block() {
    // Past the generated horizon the schedule simply has no holiday data, so a
    // weekday there trades. This is the documented limit of a data-driven
    // calendar; the horizon is chosen to be long.
    let s = nyse_schedule();
    let last = s.base_day as i64 + *s.holidays.last().unwrap() as i64;
    let (y, _, _) = civil_from_days(last);
    assert!(y >= 2046, "holiday horizon should reach at least 2046, got {y}");
}

#[test]
fn events_override_the_weekly_windows() {
    let mut s = nyse_schedule();
    // Mon 2026-09-28, 11:00 ET -- normally open.
    let midsession = 1_790_607_600i64;
    // Sat 2026-10-03, 11:00 ET -- normally closed.
    let weekend = 1_791_039_600i64;
    assert_eq!(s.state_at(midsession), MarketState::Open);
    assert_eq!(s.state_at(weekend), MarketState::Closed);

    // A deny event shuts an otherwise-open session.
    s.events = vec![Event { start: midsession - 600, end: midsession + 600, allow: false }];
    assert_eq!(s.state_at(midsession), MarketState::Closed);
    assert_eq!(s.state_at(midsession + 1_200), MarketState::Open, "outside the event, normal rules");

    // An allow event opens an otherwise-closed weekend.
    s.events = vec![Event { start: weekend - 600, end: weekend + 600, allow: true }];
    assert_eq!(s.state_at(weekend), MarketState::Open);
    assert_eq!(s.state_at(weekend + 1_200), MarketState::Closed);
}

#[test]
fn a_deny_event_beats_an_overlapping_allow() {
    let mut s = nyse_schedule();
    let t = 1_791_039_600i64; // Saturday
    s.events = vec![
        Event { start: t - 600, end: t + 600, allow: true },
        Event { start: t - 300, end: t + 300, allow: false },
    ];
    assert_eq!(s.state_at(t), MarketState::Closed, "deny must win");
    assert_eq!(s.state_at(t + 450), MarketState::Open, "only the allow covers this instant");
}

#[test]
fn an_allow_event_also_overrides_a_holiday() {
    let mut s = nyse_schedule();
    let christmas = 1_798_214_400i64; // 2026-12-25 11:00 ET
    assert_eq!(s.state_at(christmas), MarketState::Holiday);
    s.events = vec![Event { start: christmas - 60, end: christmas + 60, allow: true }];
    assert_eq!(s.state_at(christmas), MarketState::Open);
}

#[test]
fn malformed_events_are_rejected() {
    let base = ScheduleArgs {
        tz_offset_minutes: -300,
        dst_rule: DST_US,
        base_day: 20454,
        windows: vec![Window { days_mask: 0b0111110, open_minute: 570, close_minute: 960 }],
        holidays: vec![],
        early_closes: vec![],
        events: vec![],
    };
    assert!(base.validate().is_ok());

    let backwards = ScheduleArgs {
        events: vec![Event { start: 100, end: 100, allow: true }],
        ..base.clone()
    };
    assert!(backwards.validate().is_err(), "a zero-length event must be rejected");

    let too_many = ScheduleArgs {
        events: (0..MAX_EVENTS as i64 + 1)
            .map(|i| Event { start: i * 10, end: i * 10 + 5, allow: true })
            .collect(),
        ..base
    };
    assert!(too_many.validate().is_err());
}

/// The generated holiday table must cover every year it claims to, with no
/// gaps. The 2.2M-slot differential against tzdata is run out of band (see
/// README); this guards the data the differential depends on.
#[test]
fn holiday_table_has_no_gaps_across_the_horizon() {
    let s = nyse_schedule();
    let mut per_year = std::collections::BTreeMap::new();
    for off in s.holidays.iter() {
        let (y, _, _) = civil_from_days(s.base_day as i64 + *off as i64);
        *per_year.entry(y).or_insert(0) += 1;
    }
    let first = *per_year.keys().next().unwrap();
    let last = *per_year.keys().last().unwrap();
    assert_eq!(first, 2026, "horizon should start in 2026");
    assert!(last >= 2046, "horizon should reach 2046, got {last}");
    for y in first..=last {
        let n = per_year.get(&y).copied().unwrap_or(0);
        // NYSE observes 9 or 10 full closures a year: New Year's is not
        // observed when 1 January falls on a Saturday.
        assert!(
            (9..=10).contains(&n),
            "{y} has {n} holidays, expected 9 or 10"
        );
    }
}
